module.exports = [
  { name: 'Anand Sahib'},
  { name: 'Baareh Maahaa'},
  { name: 'Japji'},
  { name: 'Raag Mala'},
  { name: 'Slok Mahala 9'},
  { name: 'Ardas'},
  { name: 'Basant Ki Var'},
  { name: 'Kabyo Bach Baynti Chaupai Rehiras'},
  { name: 'Sukhmani Sahib'},
  { name: 'Arti'},
  { name: 'Chandi Di Var'},
  { name: 'Kirtan Sohila'},
  { name: 'Shabad Hazarai Patsahi 10'},
  { name: 'Tva Prasad Svaye'},
  { name: 'Asa Di Var'},
  { name: 'Jaap Sahib'},
  { name: 'Lawa'},
  { name: 'Shabad Hazarey'}];
