module.exports = [
  {"name":"Anand Sahib"},
  {"name":"Ardas"},
  {"name":"Arti"},
  {"name":"Asa Di Var"},
  {"name":"Baareh Maahaa"},
  {"name":"Basant Ki Var"},
  {"name":"Chandi Di Var"},
  {"name":"Jaap Sahib"},
  {"name":"Japji"},
  {"name":"Kabyo Bach Baynti Chaupai"},
  {"name":"Kirtan Sohila"},
  {"name":"Lawa"},
  {"name":"Raag Mala"},
  {"name":"Rehiras"},
  {"name":"Shabad Hazarai Patsahi 10"},
  {"name":"Shabad Hazarey"},
  {"name":"Slok Mahala 9"},
  {"name":"Sukhmani Sahib"},
  {"name":"Tva Prasad Svaye"}];
