export const loading = `### Loading. 
[Report](https://github.com/bogas/sikhjs/issues) if you are seeing this for a long time.
`;

  export const baanies = {
    nitnem: [
      { title: 'Japji', author: [1, 6], info: `Japji Sahib is the first sacred composition found in the main Sikh holy scripture called the Guru Granth Sahib. It is a famous and concise summary of Sikh philosophy which was compiled by the founder of Sikhism and the first spiritual guide of the Sikhs known worldwide as Guru Nanak.  The compilation consists of the Mool Mantar, an opening Salok or verse, a set of 38 Pauris or hymns and a final closing Salok. This Bani called Japji Sahib, appears at the very beginning of the Guru Granth Sahib from Page 1 to Page 8 in the Holy Book of the Sikhs Nay! of Humanity. It, the most important Bani or 'set of verses', and is lovingly recited by all Sikhs every morning. The word ‘Jap’ means to ‘recite’/‘to ‘chant’/'to stay focused onto'. ‘Ji’ is a word that is used to show respect as is the word ‘Sahib’`, },

      { title: 'Jaap Sahib', author: [39], info: `Jaap is the bani (set of hymns) uttered by Guru Gobind Singh ji, the Tenth Sikh Guru, the Tenth Nanak. It is one of the Five Banis recited by most practising Sikhs each morning and the bani that the Panj Pyare recite while preparing Amrit on the occasion of Amrit Sanchaar (Sikh Initiation), a ceremony held to admit initiates into the Khalsa Brotherhood. It is the second bani of the five in the daily morning prayer routine of a Sikh. This bani has the same place in the Dasam Granth as the Japji Sahib has in Guru Granth Sahib. Guru Gobind Singh was a worshipper of one God (Akal) this is proved by the first stanza of Jaap sahib. Guru Gobind Singh ji completed this bani before 1699, because this bani was recited during the installation of the khalsa. Professor Sahib Singh says that, " Guru Gobind SIngh went to Nahan in 1684 and lived there for approximately 3 years. During these three years guru Sahib may have composed the Jaap Sahib, the Swaiyey and the Akal Ustat. `, },

      { title: 'Tva Prasad Svaye', author: [39], info: `(Sudha Swayas) A Bani composed by Guru Gobind Singh which tells us how to worship and realise God. This Bani appears in the Dasam Granth on pages 13 to 15. Historical accounts says that htis bani was composed for bhim chand raja when gru ji was in pauta to show him that by having thousand of forces or infinite of land or kingdom one canot attain god. `, },

      { title: 'Kabyo Bach Baynti Chaupai', author: [39], info: `Benti Chaupai or Chaupai sahib is a prayer or Bani composed by tenth Sikh Guru, Guru Gobind Singh. This bani is present in Charitar 404 of Dasam Granth in Bani Ath Pakhyan Chairtar Likhyatey. This Bani is one of the five Banis recited by the initiated Sikh every morning. It is also a part of evening prayer of the Sikhs called Rehras sahib. The Benti Chaupee can be read at any time during the day to provide protection, positive focus and energy. It is short composition which usually takes less than about 5 minutes to recite at a slow pace; it is written in simple Punjabi language and can be easily understood by most speakers of this language. Chaupai is the short name for the Sikh prayer or Gurbani whose full name is Kabiobach Bainti Chaupai. This composition is part of the second most important Sikh Holy Book called the Dasam Granth. The Bani comes after the section called Charitropakhyan. Many "charitars" (tricks; deceptions) of the world are shown in Charitropakhyan. Charitars highlight negative energies that can be found on earth. After composing Charitars, the tenth master composed the section that includes this particular bani. It is an Ardas or 'request' or 'sincere plea' to God for protection. `, },

      { title: 'Anand Sahib', author: [5], info: `This Bani is part of the Nitnem (prayers) which are read by Amritdhari Sikhs in the morning. This Bani was written by Guru Amar Das, the third Guru of the Sikhs and forms part of the 5 Banis that are recited daily by baptised Sikhs. The Bani appears on pages 917 to 922 of Guru Granth Sahib, the Sikh Holy Scriptures. It is said that the person who recites this Holy Bani daily with dedication, attention and comprehension, will achieve Anand (Complete Happiness or Bliss) in life. Anand Sahib is also chanted at all religious ceremonies of the Sikhs irrespective of the nature of event, be it a marriage or death. In the beautiful composition and with the Grace of Sri Guru Amar Das, the mind and soul of a true Sikh remains steadfast and goal oriented in all circumstances of life. In an awakened mind with Guru Consciousness and intoxicated with the Nectar of Naam, one is always tuned with the Sweet Will of the Lord in all ups and downs of life, in pain and pleasure alike. His is a mind which is ever luminous with Guru Consciousness and is in perpetual intoxication of Naam and Amrit Bani, accepting without question the Hukam of the Almighty. All Dukh (Pain) and Sukh, (Pleasure) appear as the same to the devoted Sikh of the Guru. `, },

      { title: 'Rehiras', author: [1, 5, 3, 4, 39], info: `Rehiras Sahib is the evening prayer of the Sikhs, which speaks of the greatness of Waheguru. As recorded in the Guru Granth Sahib, it contains the hymns of four different Gurus; Guru Nanak, Guru Amardas, Guru Ramdas and Guru Arjan Dev. Now part of the Rehiras Sahib the Benti Chaupai, attributed to Guru Gobind Singh was added to the Bani in the late 19th century. The addition was later ratified by the supreme Sikh religious body - the Shiromani Gurudwara Prabandhak Committee. Each section of the prayer casts light on another aspect of God. It is recited after a hard days work when one is tired out. After returning home, washing up, and changing into more comfortable indoor clothing the family gathers together to recite this Bani. It adds energy to both the body and the mind allowing one to conclude their day, giving thanks to the Almighty for the completion of another successful day.  The verse speaks of the greatness of Waheguru and the ways in which ones actions assists one in attaining spiritual enlightenment, liberating one's mind and soul. This Bani assists a person when they are physically weak, financially weak or concerned with other material and earthly matters (sickness, physical weakness, lack of money or property) the mundane things of life that sometimes leaves us all feeling hopeless, unsuccessful or worthless. It elevates your mental outlook, leaving you with a fresh and positive view of things, adding energy to one's being, in both ones working and home life as well.  `, },

      { title: 'Kirtan Sohila', author: [1, 3, 4], info: `This is the night time prayer said by all Sikhs before they go to sleep. Three Sikh Gurus – Guru Nanak, Guru Ram Das and Guru Arjan - contributed five shabads in total to this bani on the pain of separation and celebrating the bliss of union with Almighty. The first three shabads were uttered by Guru Nanak, the fourth by Guru Ram Das, and the fifth by Guru Arjan Dev. It is the most harmonious Naad ever uttered. It multiplies the aura to the sensitivity of protection that it eliminates any negativity for miles and miles. When you are endangered by any species of direct or indirect source; when you want to protect yourself with the surrounding of the entire magnetic field of the earth, recite Kirtan Sohila. It is a cure for insomnia! The religious and artistic value of these hymns is superb. The first shabad visualises the union of the personal self with the Ultimate Reality. The second shabad presents the singularity of the Ultimate despite endless diversity of scriptures, teachers and philosophies. The third shabad rejects all modes of external piety and ritual, and vividly portrays the entire cosmos making harmonious worship. Instead of trays with lamps placed upon them with incense and other offerings, the skies become an integrated platter, the sun and moon the lamps, stars the beads, and all vegetation an offering of flowers. Loud chanting is replaced by the inner unstruck melody playing motionlessly. The fourth shabad explains the importance of the divine Name through which all suffering and transmigration is annulled. The fifth shabad celebrates life here in this world: we must avail ourselves of this wonderful opportunity to serve others and to win divine merit. The unknown Mystery becomes known to the enlightened person who thereafter enjoys the bliss and freedom of immortality. It is also recited before cremation, following a death. This Bani is found on pages 12 to 13 of the Sri Guru Granth Sahib, the Sikh Holy Scriptures. `},
    ],
    others: [ 
      { title: 'Ardas', author: [], info: '', },
      { title: 'Arti', author: [], info: '', },
      { title: 'Asa Di Var', author: [], info: '', },
      { title: 'Baareh Maahaa', author: [], info: '', },
      { title: 'Basant Ki Var', author: [], info: '', },
      { title: 'Chandi Di Var', author: [], info: '', },
      { title: 'Lawa', author: [], info: '', },
      { title: 'Raag Mala' , author: [], info: '', },
      { title: 'Shabad Hazarai Patsahi 10', author: [], info: '', },
      { title: 'Shabad Hazarey', author: [], info: '', },
      { title: 'Slok Mahala 9', author: [], info: '', },
      { title: 'Sukhmani Sahib', author: [], info: '', },
    ],
  };
