export default [
  {
    start: new Date('Mar 14, 2016'),
    end: new Date('Mar 14, 2016'),
    allDay: true,
    desc: 'Chet',
    title: 'Nanakshahi New Year',
  },
  {
    start: new Date('Mar 19, 2016'),
    end: new Date('Mar 19, 2016'),
    allDay: true,
    desc: 'Chet',
    title: 'Joti Jot Guru Hargobind Sahib Ji',
  },
  {
    start: new Date('Mar 24, 2016'),
    end: new Date('Mar 24, 2016'),
    allDay: true,
    desc: 'Chet',
    title: 'Hola Mohalla (2016")',
  },
  {
    start: new Date('Apr 9, 2016'),
    end: new Date('Apr 9, 2016'),
    allDay: true,
    desc: 'Chet',
    title: 'Birth of Sahibzada Jujhar Singh Ji',
  },
  {
    start: new Date('Apr 14, 2016'),
    end: new Date('Apr 14, 2016'),
    allDay: true,
    desc: 'Vaisakh',
    title: 'Vaisakhi and Birth of Khalsa',
  },
  {
    start: new Date('Apr 16, 2016'),
    end: new Date('Apr 16, 2016'),
    allDay: true,
    desc: 'Vaisakh',
    title: 'Joti Jot Guru Angad Dev Ji and Guru Har Krishan Ji, Gur Gadi Guru Amar Das Ji and Guru Tegh Bahadur Ji',
  },
  {
    start: new Date('Apr 18, 2016'),
    end: new Date('Apr 18, 2016'),
    allDay: true,
    desc: 'Vaisakh',
    title: 'Birth of Guru Angad Dev Ji and Guru Tegh Bahadur Ji',
  },
  {
    start: new Date('May 2, 2016'),
    end: new Date('May 2, 2016'),
    allDay: true,
    desc: 'Vaisakh',
    title: 'Birth of Guru Arjan Dev Ji',
  },
  {
    start: new Date('May 15, 2016'),
    end: new Date('May 15, 2016'),
    allDay: true,
    desc: 'Jeth',
    title: 'Jeth',
  },
  {
    start: new Date('May 23, 2016'),
    end: new Date('May 23, 2016'),
    allDay: true,
    desc: 'Jeth',
    title: 'Birth of Guru Amar Das Ji',
  },
  {
    start: new Date('Jun 4, 2016'),
    end: new Date('Jun 4, 2016'),
    allDay: true,
    desc: 'Jeth',
    title: 'Birthday of Bhagat Puran Singh Ji',
  },
  {
    start: new Date('Jun 11, 2016'),
    end: new Date('Jun 11, 2016'),
    allDay: true,
    desc: 'Jeth',
    title: 'Gur Gadi Guru Hargobind Sahib Ji',
  },
  {
    start: new Date('Jun 15, 2016'),
    end: new Date('Jun 15, 2016'),
    allDay: true,
    desc: 'Harh',
    title: 'Harh',
  },
  {
    start: new Date('Jun 16, 2016'),
    end: new Date('Jun 16, 2016'),
    allDay: true,
    desc: 'Harh',
    title: 'Martyrdom of Guru Arjan Dev Ji',
  },
  {
    start: new Date('Jul 2, 2016'),
    end: new Date('Jul 2, 2016'),
    allDay: true,
    desc: 'Harh',
    title: 'Foundation of Akal Takht',
  },
  {
    start: new Date('Jul 5, 2016'),
    end: new Date('Jul 5, 2016'),
    allDay: true,
    desc: 'Harh',
    title: 'Birth of Guru Hargobind Sahib Ji',
  },
  {
    start: new Date('Jul 16, 2016'),
    end: new Date('Jul 16, 2016'),
    allDay: true,
    desc: 'Sawaan',
    title: 'Sawaan',
  },
  {
    start: new Date('Jul 23, 2016'),
    end: new Date('Jul 23, 2016'),
    allDay: true,
    desc: 'Sawaan',
    title: 'Birth of Guru Har Krishan Ji',
  },
  {
    start: new Date('Aug 5, 2016'),
    end: new Date('Aug 5, 2016'),
    allDay: true,
    desc: 'Sawaan',
    title: 'Barsi Bhagat Puran Singh Ji',
  },
  {
    start: new Date('Aug 8, 2016'),
    end: new Date('Aug 8, 2016'),
    allDay: true,
    desc: 'Sawaan',
    title: 'Morcha Guru Ka Bagh',
  },
  {
    start: new Date('Aug 16, 2016'),
    end: new Date('Aug 16, 2016'),
    allDay: true,
    desc: 'Bhadon',
    title: 'Bhadon',
  },
  {
    start: new Date('Aug 30, 2016'),
    end: new Date('Aug 30, 2016'),
    allDay: true,
    desc: 'Bhadon',
    title: 'Completion of Adi Granth',
  },
  {
    start: new Date('Sept 1, 2016'),
    end: new Date('Sept 1, 2016'),
    allDay: true,
    desc: 'Bhadon',
    title: 'Prakash Guru Granth Sahib',
  },
  {
    start: new Date('Sept 12, 2016'),
    end: new Date('Sept 12, 2016'),
    desc: 'Bhadon',
    allDay: true,
    title: 'Battle of Saragarhi',
  },
  {
    start: new Date('Sept 15, 2016'),
    end: new Date('Sept 15, 2016'),
    desc: 'Assu',
    allDay: true,
    title: 'Assu',
  },
  {
    start: new Date('Sept 16, 2016'),
    end: new Date('Sept 16, 2016'),
    allDay: true,
    desc: 'Assu',
    title: 'Joti Jot Guru Amar Das Ji and Guru Ram Das Ji, Gur Gadi Guru Ram Das Ji and Guru Arjan Devi Ji',
  },
  {
    start: new Date('Sept 18, 2016'),
    end: new Date('Sept 18, 2016'),
    allDay: true,
    desc: 'Assu',
    title: 'Gur Gadi Guru Angad Dev Ji',
  },
  {
    start: new Date('Sept 22, 2016'),
    end: new Date('Sept 22, 2016'),
    allDay: true,
    title: 'Joti Jot Guru Nanak Dev Ji',
    desc: 'Assu',
  },
  {
    start: new Date('Oct 9, 2016'),
    end: new Date('Oct 9, 2016'),
    allDay: true,
    title: 'Birth of Guru Ram Das Ji',
    desc: 'Assu',
  },
  {
    start: new Date('Oct 15, 2016'),
    end: new Date('Oct 15, 2016'),
    allDay: true,
    desc: 'Katik',
    title: 'Katik',
  },
  {
    start: new Date('Oct 20, 2016'),
    end: new Date('Oct 20, 2016'),
    allDay: true,
    title: 'Joti Jot Guru Har Rai Gur Gadi Guru Har Krishan Ji Guru Granth Sahib Ji',
    desc: 'Katik',
  },
  {
    start: new Date('Oct 21, 2016'),
    end: new Date('Oct 21, 2016'),
    allDay: true,
    desc: 'Katik',
    title: 'Joti Jot Guru Gobind Singh Ji',
  },
  {
    start: new Date('Oct 30, 2016'),
    end: new Date('Oct 30, 2016'),
    allDay: true,
    desc: 'Katik',
    title: 'Bandi Chhorh Divas (2016")',
  },
  {
    start: new Date('Nov 14, 2016'),
    end: new Date('Nov 14, 2016'),
    allDay: true,
    desc: 'Maghar',
    title: 'Birth of Guru Nanak (2016")',
  },
  {
    start: new Date('Nov 24, 2016'),
    end: new Date('Nov 24, 2016'),
    allDay: true,
    desc: 'Maghar',
    title: 'Shaheedi Guru Tegh Bahadur Ji and Gur Gadi Guru Gobind Singh Ji',
  },
  {
    start: new Date('Nov 25, 2016'),
    end: new Date('Nov 25, 2016'),
    allDay: true,
    title: 'Birth of Guru Nanak Dev Ji',
    desc: 'Maghar',
  },
  {
    start: new Date('Nov 28, 2016'),
    end: new Date('Nov 28, 2016'),
    allDay: true,
    title: 'Birth of Sahibzada Zorawar Singh',
    desc: 'Maghar',
  },
  {
    start: new Date('Dec 12, 2016'),
    end: new Date('Dec 12, 2016'),
    allDay: true,
    desc: 'Maghar',
    title: 'Birth of Sahibzada Fateh Singh',
  },
  {
    start: new Date('Dec 14, 2016'),
    end: new Date('Dec 14, 2016'),
    allDay: true,
    desc: 'Poh',
    title: 'Poh',
  },
  {
    start: new Date('Dec 21, 2016'),
    end: new Date('Dec 21, 2016'),
    allDay: true,
    desc: 'Poh',
    title: 'Shaheedi Sahibzada Ajit Singh Ji and Sahibzada Jujhar Singh Ji (Vaday Sahibzaday)',
  },
  {
    start: new Date('Dec 26, 2016'),
    end: new Date('Dec 26, 2016'),
    allDay: true,
    desc: 'Poh',
    title: 'Shaheedi Sahibzada Zorawar Singh Ji and Sahibzada Fateh Singh Ji (Chotte Sahibzaday)',
  },
  {
    start: new Date('Jan 5, 2017'),
    end: new Date('Jan 5, 2017'),
    allDay: true,
    desc: 'Poh',
    title: 'Birth of Guru Gobind Singh Ji',
  },
  {
    start: new Date('Jan 13, 2017'),
    end: new Date('Jan 13, 2017'),
    allDay: true,
    desc: 'Magh',
    title: 'Magh',
  },
  {
    start: new Date('Jan 18, 2017'),
    end: new Date('Jan 18, 2017'),
    allDay: true,
    desc: 'Magh',
    title: 'Birth of Bhai Himmat Singh Ji',
  },
  {
    start: new Date('Jan 26, 2017'),
    end: new Date('Jan 26, 2017'),
    allDay: true,
    desc: 'Magh',
    title: 'Birth of Baba Deep Singh Ji',
  },
  {
    start: new Date('Jan 31, 2017'),
    end: new Date('Jan 31, 2017'),
    allDay: true,
    title: 'Birth of Guru Har Rai Ji',
    desc: 'Magh',
  },
  {
    start: new Date('Feb 11, 2017'),
    end: new Date('Feb 11, 2017'),
    allDay: true,
    title: 'Birth of Sahibzada Ajit Singh Ji',
    desc: 'Magh',
  },
  {
    start: new Date('Feb 12, 2017'),
    end: new Date('Feb 12, 2017'),
    allDay: true,
    desc: 'Phagun',
    title: 'Phagun',
  },
  {
    start: new Date('Feb 21, 2017'),
    end: new Date('Feb 21, 2017'),
    allDay: true,
    desc: 'Phagun',
    title: 'Saka Nankana Sahib, Jaito Morcha',
  },
  {
    start: new Date('Mar 13, 2017'),
    end: new Date('Mar 13, 2017'),
    desc: 'Phagun',
    allDay: true,
    title: 'Hola Mohalla (2017, 2016"), End of Nanakshahi calendar year',
  },
];
